//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingApp.FileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileService.IFileTransportService")]
    public interface IFileTransportService {
        
        // CODEGEN: 消息 FileUploadMessage 的包装名称(FileUploadMessage)以后生成的消息协定与默认值(UploadFile)不匹配
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="UploadFile")]
        void UploadFile(InvoicingApp.FileService.FileUploadMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetFileList", ReplyAction="http://tempuri.org/IFileTransportService/GetFileListResponse")]
        string[] GetFileList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransportService/GetFile", ReplyAction="http://tempuri.org/IFileTransportService/GetFileResponse")]
        System.IO.Stream GetFile(string fileName);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileData;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(string FileName, System.IO.Stream FileData) {
            this.FileName = FileName;
            this.FileData = FileData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileTransportServiceChannel : InvoicingApp.FileService.IFileTransportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileTransportServiceClient : System.ServiceModel.ClientBase<InvoicingApp.FileService.IFileTransportService>, InvoicingApp.FileService.IFileTransportService {
        
        public FileTransportServiceClient() {
        }
        
        public FileTransportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileTransportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void InvoicingApp.FileService.IFileTransportService.UploadFile(InvoicingApp.FileService.FileUploadMessage request) {
            base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string FileName, System.IO.Stream FileData) {
            InvoicingApp.FileService.FileUploadMessage inValue = new InvoicingApp.FileService.FileUploadMessage();
            inValue.FileName = FileName;
            inValue.FileData = FileData;
            ((InvoicingApp.FileService.IFileTransportService)(this)).UploadFile(inValue);
        }
        
        public string[] GetFileList() {
            return base.Channel.GetFileList();
        }
        
        public System.IO.Stream GetFile(string fileName) {
            return base.Channel.GetFile(fileName);
        }
    }
}
